In [45]:
# module of generating csv from from data.stats.gov.cn html
import re
import pandas as pd
import numpy as np

def transform_text(text, newline_patterns=None, comma_patterns=None, column_names=None):

    # transform html to csv-formatted string
    newline_patterns = newline_patterns or []
    comma_patterns = comma_patterns or []

    for pattern in newline_patterns:
        text = re.sub(pattern, "\n", text)

    for pattern in comma_patterns:
        text = re.sub(pattern, ",", text)

    ending = '</span></div></td></tr>'
    text = re.sub(ending, "", text)

    text = re.sub("<!---->", "", text)

    text = re.sub(r"年(\d{1})月", r"-0\1-01", text)
    text = re.sub(r"年(\d{2})月", r"-\1-01", text)

    # transform string into csv
    from io import StringIO

    df = pd.read_csv(
        StringIO(text), 
        names = column_names,
        parse_dates=[column_names[0]]
    )

    df.iloc[:, 1:] = df.iloc[:, 1:] - 100

    return df

In [40]:
input_text = """
<tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_104 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_105 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_106 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_107 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><!---->
"""

newline_patterns = [
    r'<tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_102 is-center\s+is-hidden el-table__cell"><div class="cell"><!----><span class="">'
]

comma_patterns = [
    r'</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_\d+ is-center\s+el-table__cell"><div class="cell"><!----><span class="">'
]

column_names = [
    'Date','PPI Output - MoS (Food) MoM','PPI Output - MoS (Apparel) MoM','PPI Output - MoS (Common Daily Necessities) MoM','PPI Output - MoS (Durable) MoM'
]

ppi_output_mos_mom = transform_text(
    input_text,
    newline_patterns,
    comma_patterns,
    column_names
)

ppi_output_mos_mom.head()

,Date,PPI Output - MoS (Food) MoM,PPI Output - MoS (Apparel) MoM,PPI Output - MoS (Common Daily Necessities) MoM,PPI Output - MoS (Durable) MoM
0,2026-04-01,-0.4,-0.1,0.1,0.1
1,2026-03-01,-0.2,-0.1,0.1,-0.1
2,2026-02-01,0.0,-0.4,-0.2,0.3
3,2026-01-01,-0.1,-0.3,-0.1,0.3
4,2025-12-01,-0.1,0.2,0.5,-0.2

In [5]:
input_text = """
<tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2026年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2025年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2024年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2023年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2022年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2021年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2020年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2019年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2018年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2017年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2016年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2015年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2014年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2013年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2012年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">107.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">107.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2011年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2010年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2009年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">107.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">109.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">109.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">104.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">111.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">111.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">112.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">111.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2008年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">110.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">109.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">108.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">107.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2007年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2006年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2005年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">103.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">102.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">106.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2004年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2003年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">92.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2002年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2001年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">104.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">94.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">95.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">94.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">94.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">93.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">2000年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">94.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">92.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">94.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">96.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.6</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.2</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">92.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">94.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">92.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1999年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">92.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">95.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">92.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">94.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">95.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">105.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">95.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">93.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">92.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">94.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">95.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">96.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">90.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">96.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">91.7</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1998年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">103.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">102.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年9月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.3</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年8月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年7月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">98.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年6月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">101.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">97.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年5月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年4月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">101.1</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">100.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.2</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.1</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年3月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">96.0</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年2月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">96.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">97.4</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1997年1月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">97.3</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">99.9</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.9</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1996年12月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">102.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">98.5</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">98.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">94.5</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1996年11月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">103.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">95.7</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.0</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">93.8</span></div></td></tr><tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">1996年10月</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_116 is-center  el-table__cell"><div class="cell"><!----><span class="">104.6</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_117 is-center  el-table__cell"><div class="cell"><!----><span class="">95.4</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_118 is-center  el-table__cell"><div class="cell"><!----><span class="">100.8</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_119 is-center  el-table__cell"><div class="cell"><!----><span class="">95.8</span></div></td></tr><!---->
"""


newline_patterns = [
    r'<tr class="el-table__row"><td rowspan="1" colspan="1" class="el-table_1_column_114 is-center  is-hidden el-table__cell"><div class="cell"><!----><span class="">'
]

comma_patterns = [
    r'</span></div></td><td rowspan="1" colspan="1" class="el-table_1_column_\d+ is-center\s+el-table__cell"><div class="cell"><!----><span class="">'
]

column_names = [
    'Date','PPI Output - MoS (Food) YoY','PPI Output - MoS (Apparel) YoY','PPI Output - MoS (Common Daily Necessities) YoY','PPI Output - MoS (Durable) YoY'
]

ppi_output_mos_yoy = transform_text(
    input_text,
    newline_patterns,
    comma_patterns,
    column_names
)

ppi_output_mos_yoy.head()

,Date,PPI Output - MoS (Food) YoY,PPI Output - MoS (Apparel) YoY,PPI Output - MoS (Common Daily Necessities) YoY,PPI Output - MoS (Durable) YoY
0,2026-04-01,-1.9,-1.1,-1.1,-0.3
1,2026-03-01,-1.7,-1.1,-1.4,-1.0
2,2026-02-01,-1.8,-1.0,-1.8,-1.6
3,2026-01-01,-1.9,-0.7,-1.8,-1.8
4,2025-12-01,-1.5,-0.1,1.4,-3.5

In [49]:
ppi_output_general = pd.read_csv('CN PPI Output General (%).csv')
ppi_output_general['Date'] = pd.to_datetime(ppi_output_general['Date'])

df = ppi_output_general.merge(ppi_output_mos_yoy, on='Date').merge(ppi_output_mos_mom, on="Date")

df.head()

,Date,PPI Output YoY,PPI Output - Means of Production YoY,PPI Output - Means of Subsistence YoY,PPI Output MoM,PPI Output - Means of Production MoM,PPI Output - Means of Subsistence MoM,PPI Output - MoS (Food) YoY,PPI Output - MoS (Apparel) YoY,PPI Output - MoS (Common Daily Necessities) YoY,PPI Output - MoS (Durable) YoY,PPI Output - MoS (Food) MoM,PPI Output - MoS (Apparel) MoM,PPI Output - MoS (Common Daily Necessities) MoM,PPI Output - MoS (Durable) MoM
0,2026-04-01,2.8,3.8,-1.0,1.7,2.1,-0.1,-1.9,-1.1,-1.1,-0.3,-0.4,-0.1,0.1,0.1
1,2026-03-01,0.5,1.0,-1.3,1.0,1.3,-0.1,-1.7,-1.1,-1.4,-1.0,-0.2,-0.1,0.1,-0.1
2,2026-02-01,-0.9,-0.7,-1.6,0.4,0.5,0.0,-1.8,-1.0,-1.8,-1.6,0.0,-0.4,-0.2,0.3
3,2026-01-01,-1.4,-1.3,-1.7,0.4,0.5,0.1,-1.9,-0.7,-1.8,-1.8,-0.1,-0.3,-0.1,0.3
4,2025-12-01,-1.9,-2.1,-1.3,0.2,0.3,0.0,-1.5,-0.1,1.4,-3.5,-0.1,0.2,0.5,-0.2

In [51]:
col = df.columns.drop('Date')
df[col] = np.round(df[col], 1)
df.to_csv("output.csv", index=False)